### ISSUE TITLE
Build fails with the following error message

### ISSUE THREAD

**Issue by fuzziebrain** [fuzziebrain/oci-le-cert-manager#5]
```
Collecting cryptography>=2.1.4 (from certbot->-r /tmp/requirements.txt (line 1))
  Downloading https://files.pythonhosted.org/packages/9b/77/461087a514d2e8ece1c975d8216bc03f7048e6090c5166bc34115afdaa53/cryptography-3.4.7.tar.gz (546kB)
    Complete output from command python setup.py egg_info:
    
            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:
    
            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-9icj1f8h/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-9icj1f8h/cryptography/
The command '/bin/sh -c yum install -y         vi         jq         python3         python3-pip &&     rm -rf /var/cache/yum &&     pip3 install -r /tmp/requirements.txt &&     rm -f /tmp/requirements.txt' returned a non-zero code: 1

```

**Comment by fuzziebrain** [comment]
Need to upgrade pip before installing dependencies:

```bash
pip3 install --upgrade pip
```

See https://github.com/frappe/easy_install/issues/19

**Comment by raner** [comment]
@fuzziebrain Did upgrading `pip` actually solve this problem for you? I'm having a similar issue (in a different project) despite being on the very latest version of `pip` (`21.1.2` as of today). Did you find another solution to get around this problem?

**Comment by fuzziebrain** [comment]
> @fuzziebrain Did upgrading `pip` actually solve this problem for you? I'm having a similar issue (in a different project) despite being on the very latest version of `pip` (`21.1.2` as of today). Did you find another solution to get around this problem?

It did. I'll test it again though and let you know.

**Comment by fuzziebrain** [comment]
Reattempted a built today and this doesn't appear to be an issue any more. Will close.

**Comment by fuzziebrain** [comment]
Reopening this issue.  Just encountered the issue again.

**Comment by AlecKotovichSAM** [comment]
I have encountered the same problem during install

My environment:
```
$ uname -a
Linux master-public-1 5.11.0-1025-oracle frappe/bench#27~20.04.1-Ubuntu SMP Fri Jan 7 18:58:08 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
```
